### ISSUE TITLE
[question] does the latest version not precompile the templates and defer compilation to runtime?

### ISSUE THREAD

**Issue by sankargorthi** [kewah/component-builder-handlebars#5]
Am I reading that correctly?

**Comment by timaschew** [comment]
why do you think that it is not precompiled anymore?

**Comment by timaschew** [comment]
I only know how jade templates look like when they are compiled, sure, they are looking very different to this: 

```js
Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  return "<div id=\"home\">You're at {home}</div>\n";
  })
```

I think @kewah can give the best answer on this ;)

**Comment by kewah** [comment]
Yes, templates are precompiled during the build step. See: https://github.com/kewah/component-builder-handlebars/blob/784c238ae3ae40e8471f158a22242b8cef77a99b/index.js#L29

Do you have an issue with it ?

**Comment by sankargorthi** [comment]
In my example, the end result of the component@1 build has the non-tokenised templates (comparing against the result of component@0.19.9 with this plugin at v0.2.0)

https://github.com/componentjs/bundler-example

**Comment by sankargorthi** [comment]
```javascript
require.register("./lib/home/home.hbs", function (exports, module) {
module.exports = Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {
  this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Handlebars.helpers); data = data || {};
  


  return "<div id=\"home\">You're at {home}</div>\n";
  })
});
```

**Comment by kewah** [comment]
It seems to be a typo in home.hbs template: `{home}` should be written `{{home}}`.

In the tests or repo's [example](https://github.com/kewah/component-builder-handlebars/blob/master/example/builder.js) (`npm run example`) I get precompiled templates.

**Comment by sankargorthi** [comment]
Oh! Whoops!

**Comment by sankargorthi** [comment]
That fixed it! I'm a dimbulb.
